#!/usr/bin/env ruby

# Imports 
require 'fileutils'
require 'rake/contrib/ftptools'

desc "Runs Tests"
task :test do
    puts "Running Tests for " + ENV['game']
end

desc "Creates folder"
task :create_folder do

	puts "Checking if 'Deploys' Directory exists"

	if ! File.directory? 'Deploys'
	    Dir.mkdir("Deploys")
	    puts "Created 'Deploys' Directory"
	end

	puts 'Deploying application ' + ENV['game']

	t = Time.now().strftime("%Y%m%d_%H%M");

	dir_root = "Deploys/" +ENV['game'] + t
	dir_ex = dir_root + "/Applications"
	Dir.mkdir(dir_root)
	Dir.mkdir(dir_ex)
	FileUtils.cp("game.js", dir_root)
	FileUtils.cp_r("Images", dir_root)
	FileUtils.cp_r('Applications/' + ENV['game'], dir_ex)

	puts dir_root
end


desc "Uploads the project to the server using ftp."
task :upload_project do
  Rake::FtpUploader.connect(ENV['path_on_server'], ENV['hostname'], ENV['user'], ENV['password']) do |ftp|
    ftp.verbose = true
    ftp.upload_files(ENV['project_path'] + "/**/*")
  end
end

desc "Runs all common tasks"
task :default => [:test,:create_folder] do
    
end
